# Generated by Django 5.2.6 on 2025-09-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='update',
        ),
    ]
